{
  "formatVersion": "1.1",
  "component": {
    "group": "ru.lytvenkovmv",
    "module": "logging-starter",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "logging-starter-1.0-SNAPSHOT.jar",
          "url": "logging-starter-1.0-SNAPSHOT.jar",
          "size": 1153,
          "sha512": "80165f3b77255415c281dc751b63fa440877b8179a03082b8e2d50a347322450dba98671a6f2ec20f1f4e3723bcb0fd5e152144c08f1da5daec93b87386acf44",
          "sha256": "a10c434c2bcc36cc64a2404138bc7e0c8f1d2ef6d52d9b3680c640d4ef73eeed",
          "sha1": "d7ce90146ebf594c27214da1a3ea7d10984293ec",
          "md5": "f0e5bb086651286eb501d42ff7b151ff"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "logging-starter-1.0-SNAPSHOT.jar",
          "url": "logging-starter-1.0-SNAPSHOT.jar",
          "size": 1153,
          "sha512": "80165f3b77255415c281dc751b63fa440877b8179a03082b8e2d50a347322450dba98671a6f2ec20f1f4e3723bcb0fd5e152144c08f1da5daec93b87386acf44",
          "sha256": "a10c434c2bcc36cc64a2404138bc7e0c8f1d2ef6d52d9b3680c640d4ef73eeed",
          "sha1": "d7ce90146ebf594c27214da1a3ea7d10984293ec",
          "md5": "f0e5bb086651286eb501d42ff7b151ff"
        }
      ]
    }
  ]
}
