{
  "formatVersion": "1.1",
  "component": {
    "group": "ru.lytvenkovmv",
    "module": "logging-starter",
    "version": "1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "logging-starter-1.2-SNAPSHOT.jar",
          "url": "logging-starter-1.2-SNAPSHOT.jar",
          "size": 12448,
          "sha512": "784fb6dbccbc8e5edec2e5b020bb4a7b61fab4ac67cc2fed9cef634aed32cae4661b0de48dedb84e0c7e5fc0d06b6a36d512f99be3674deebb2c1a6ed76e449e",
          "sha256": "fe4575dbc7e10c49b5913d3ca1f2e58d0dc3d857426f0daf6dffde2d3f83955b",
          "sha1": "ea02ff7d92ca1937da55aa61ee16ed59af1cad16",
          "md5": "876f418458cb88619dc67071b869a3ae"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "3.3.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "3.3.5"
          }
        },
        {
          "group": "com.jayway.jsonpath",
          "module": "json-path",
          "version": {
            "requires": "2.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "logging-starter-1.2-SNAPSHOT.jar",
          "url": "logging-starter-1.2-SNAPSHOT.jar",
          "size": 12448,
          "sha512": "784fb6dbccbc8e5edec2e5b020bb4a7b61fab4ac67cc2fed9cef634aed32cae4661b0de48dedb84e0c7e5fc0d06b6a36d512f99be3674deebb2c1a6ed76e449e",
          "sha256": "fe4575dbc7e10c49b5913d3ca1f2e58d0dc3d857426f0daf6dffde2d3f83955b",
          "sha1": "ea02ff7d92ca1937da55aa61ee16ed59af1cad16",
          "md5": "876f418458cb88619dc67071b869a3ae"
        }
      ]
    }
  ]
}
