{
  "formatVersion": "1.1",
  "component": {
    "group": "ru.lytvenkovmv",
    "module": "logging-starter",
    "version": "1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "logging-starter-1.2-SNAPSHOT-plain.jar",
          "url": "logging-starter-1.2-SNAPSHOT-plain.jar",
          "size": 7072,
          "sha512": "b84b999ea2952bb63d2646ab76e24cfa6cc05a71286b96032d75a980b59e05c0b3c8e6afba9732f692c89fa80ec3896fbed0d625bf69709c3fb64dead35f4f13",
          "sha256": "2c34546e1b8b9034fa71e1a45cb62857579c607eb4e66081874c06c4c6534a5e",
          "sha1": "e42c4958288f5663da6a1cd072e62aa4db9ea9e7",
          "md5": "8b536fbc394fd702a5c719d51c707ee2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "3.3.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "3.3.5"
          }
        }
      ],
      "files": [
        {
          "name": "logging-starter-1.2-SNAPSHOT-plain.jar",
          "url": "logging-starter-1.2-SNAPSHOT-plain.jar",
          "size": 7072,
          "sha512": "b84b999ea2952bb63d2646ab76e24cfa6cc05a71286b96032d75a980b59e05c0b3c8e6afba9732f692c89fa80ec3896fbed0d625bf69709c3fb64dead35f4f13",
          "sha256": "2c34546e1b8b9034fa71e1a45cb62857579c607eb4e66081874c06c4c6534a5e",
          "sha1": "e42c4958288f5663da6a1cd072e62aa4db9ea9e7",
          "md5": "8b536fbc394fd702a5c719d51c707ee2"
        }
      ]
    }
  ]
}
